name: Hello

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo Hello
